#include "z80.h"

op_t op_tab[] = {
  {"NOP", "00", "NOP", &z80_nop},
  {"LD BC, nn", "01", "16bit operation, 8 firsts in B, next 8 bits in C", &z80_ld_bc},
  {"LD (BC), nn", "02", "16bit address operation, 8", &z80_ld_adr_bc},
  {"INC BC", "03", "Increment by one the value of BC", &z80_inc_bc},
  {"INC B", "04", "Increment by one the value stored in B", &z80_inc_b},
  {"DEC B", "05", "Subtract 1 to registry", &z80_dec_b},
  {"LD B, n", "06", "Load n in B", &z80_ld_b},
  {"RLC A", "07", "Rotate the content of A to the left", &z80_rlc_a},
  {"LD (nn), SP", "08", "Put the value of stack pointer to the address of nn", &z80_ld_adress_n_sp},
  {"LD HL,BC", "09", "Load the value of B in H and value of C in L", &z80_ld_hl_bc},
  {"LD A, (BC)", "0A", "Load the value stored at the address of BC in A", &z80_ld_a_adr_bc},
  {"DEC BC","0B", "Subtract 1 to BC", &z80_dec_bc},
  {"INC C", "0C", "Increment the value of C by one", &z80_inc_c},
  {"DEC C", "0D", "Subtract 1 to C", &z80_dec_c},
  {"LD C, n", "0E", "Load n in C", &z80_ld_c},
  {"RRC C", "0F", "Rotate the value of C to the right", &z80_rrc_c},
  {"STOP", "10", "STOP", &z80_stop},
  {"LD DE, nn", "11", "16bit operation. 8 firsts in D, next 8 bits in E", &z80_ld_de},
  {"LD (DE), A", "12", "Load the value of A at address pointed by (DE)", &z80_adr_de_a},
  {"INC DE", "13", "Increment the value of DE", &z80_inc_de},
  {"INC D", "14", "Increment D", &z80_inc_d},
  {"DEC D", "15", "Subtract 1 to D", &z80_dec_d},
  {"LD D, n" "16", "Load n in D", &z80_ld_d},
  {"RL A", "17", "Rotate content of A to the left", &z80_rl_a},
  {"JR n", "18", "Conditional jump", &z80_jr},
  {"ADD HL, DE","19", "Add D to H, E to L", &z80_add_hl_de},
  {"LD A, (DE)","1A","Take the value stored at (DE) and load it in A", &z80_ld_a_adr_de},
  {"DEC DE", "1B", "Decrement DE", &z80_dec_de},
  {"INC E", "1C", "Increment E", &z80_inc_e},
  {"DEC E", "1D", "Decrement E", &z80_dec_e},
  {"LD E, n". "1E", "Load n in E", &z80_ld_e},
  {"RR A", "1F", "Rotate content of A to the right", &z80_rr_a},
  {"JR NZ, n", "20", "Conditional jump if not 0 goto n",&z80_jr_nz_adr},
  {"LD HL, nn", "21", "16bit operation. 8 firsts in H, next 8 bits in L", &z80_ld_hl},
  {"LDI (HL), n", "22", "Load n at the address pointed by (HL) and inc HL", &z80_ldi_adr_hl},
  {"INC HL", "23", "Increment HL", &z80_inc_hl},
  {"INC H", "24", "Increment H", &z80_inc_h},
  {"DEC H", "25", "Subtract 1 by H", &z80_dec_h},
  {"LD H, n", "26", "Load n in H", &z80_ld_h_adr},
  {"DAA", "27", "Adjust A to BCD addition", &z80_daa},
  {"JR Z, n", "28", "Relative conditional jump if last result 0 goto n", &z80_jr_z},
  {"ADD HL, HL", "29", "Add HL to HL", &z80_add_hl_hl},
  {"LDI A, (HL)", "2A", "Load value stored at the address pointed by (HL) in A and inc HL", &z80_ldi_a_adr_hl},
  {"DEC HL", "2B", "Decrement HL", &z80_dec_hl},
  {"INC L", "2C", "Increment L", &z80_inc_l},
  {"DEC L", "2D", "Decrement L", &z80_dec_l},
  {"LD L, n", "2E", "Load ...", &z80_ld_l},
  {"CPL", "2F", "Complement", &z80_cpl},
  {"JR NC, n", "30", "Jumps to given address if carry = 0", &z80_jr_nc},
  {"LD SP, nn", "31", "Load nn in SP", &z80_ld_sp},
  {"LDD (HL), A", "32", "Save A to address (HL), decrement HL", &z80_ldd_adr_hl_a},
  {"INC SP", "33", "Increment SP", &z80_inc_sp},
  {"INC (HL)", "34", "Inc (HL) value", &z80_inc_val_adr_hl},
  {"DEC (HL)", "35", "Dec (HL) value", &z80_dec_val_adr_hl},
  {"LD (HL), n", "36", "Save n at adr pointed by (HL)", &z80_ld_adr_hl},
  {"SCF", "37", "Set carry flag", &z80_scf},
  {"JR C, n", "38", "Relative jmp if carry = 1 goto n", &z80_jr_c},
  {"ADD HL, SP", "39", "Add SP to HL", &z80_add_hl_sp},
  {"LDD A, (HL)", "3A", "Load value of (HL) in A, decrement (HL)", &z80_ldd_a_adr_hl},
  {"DEC SP", "3B", "Decrement SP", &z80_dec_sp},
  {"INC A", "3C", "Increase A", &z80_inc_a},
  {"DEC A", "3D", "Decrease A", &z80_dec_a},
  {"LD A, n", "3E", "Load n in A", &z80_ld_a},
  {"CCF", "3F", "Complement carry flag, of C flag is set then reset it. if C flag is reset, then  set it", &z80_ccf},
  {"LD B,B", "40", "Load B in B", &z80_ld_b_b},
  {"LD B,C", "41", "Load C in B", &z80_ld_b_c},
  {"LD B,D", "42", "Load D in B", &z80_ld_b_d},
  {"LD B,E", "43", "Load E in B", &z80_ld_b_e},
  {"LD B,H", "44", "Load H in B", &z80_ld_b_h},
  {"LD B,L", "45", "Load L in B", &z80_ld_b_l},
  {"LD B,(HL)", "46", "Load the address of (HL) in B", &z80_ld_b_adr_hl},
  {"LD B,A", "47", "Load A in B", &z80_ld_b_a},
  {"LD C,B", "48", "Load B in C", &z80_ld_c_b},
  {"LD C,C", "49", "Load C in C", &z80_ld_c_c},
  {"LD C,D", "4A", "Load D in C", &z80_ld_c_d},
  {"LD C,E", "4B", "Load E in C", &z80_ld_c_e},
  {"LD C,H", "4C", "Load H in C", &z80_ld_c_h},
  {"LD C,L", "4D", "Load L in C", &z80_ld_c_l},
  {"LD C,(HL)", "4E", "Load the value stored on the address of (0xFF00 + (HL)) in C", &z80_ld_c_adr_hl},
  {"LD C,A", "4F", "Load A in C", &z80_ld_c_a},
  {"LD D,B", "50", "Load B in D", &z80_ld_d_b},
  {"LD D,C", "51", "Load C in D", &z80_ld_d_c},
  {"LD D,D", "52", "Load D in D", &z80_ld_d_d},
  {"LD D,E", "53", "Load E in D", &z80_ld_d_e},
  {"LD D,H", "54", "Load H in D", &z80_ld_d_h},
  {"LD D,L", "55", "Load L in D", &z80_ld_d_l},
  {"LD D,(HL)", "56", "Load the value stored in the address ((0xFF00) + HL) in D", &z80_ld_d_adr_hl},
  {"LD D,A", "57", "Load A in D", &z80_ld_d_a},
  {"LD E,B", "58", "Load B in E", &z80_ld_e_b},
  {"LD E,C", "59", "Load C in E", &z80_ld_e_c},
  {"LD E,D", "5A", "Load D in E", &z80_ld_e_d},
  {"LD E,E", "5B", "Load E in E", &z80_ld_e_e},
  {"LD E,H", "5C", "Load H in E", &z80_ld_e_h},
  {"LD E,L", "5D", "Load L in E", &z80_ld_e_l},
  {"LD E,(HL)", "5E", "Load the value stored in the address ((0xFF00) + HL) in E", &z80_ld_e_adr_hl},
  {"LD E,A", "5F", "Load A in E", &z80_ld_e_a},
  {"LD H,B", "60", "Load B in H", &z80_ld_h_b},
  {"LD H,C", "61", "Load C in H", &z80_ld_h_c},
  {"LD H,D", "62", "Load D in H", &z80_ld_h_d},
  {"LD H,E", "63", "Load E in H", &z80_ld_h_e},
  {"LD H,H", "64", "Load H in H", &z80_ld_h_h},
  {"LD H,L", "65", "Load L in H", &z80_ld_h_l},
  {"LD H,(HL)","66", "Load the value stored in the address ((0xFF00) + HL) in H", &z80_ld_h_adr_hl},
  {"LD H,A", "67", "Load A in H", &z80_ld_h_a},
  {"LD L,B", "68", "Load B in L", &z80_ld_l_b},
  {"LD L,C", "69", "Load C in L", &z80_ld_l_c},
  {"LD L,D", "6A", "Load D in L", &z80_ld_l_d},
  {"LD L,E", "6B", "Load E in L", &z80_ld_l_e},
  {"LD L,H", "6C", "Load H in L", &z80_ld_l_h},
  {"LD L,L", "6D", "Load L in L", &z80_ld_l_l},
  {"LD L,(HL)", "6E", "Load the value stored in the address ((0xFF00) + HL) in L", &z80_ld_l_adr_hl},
  {"LD L,A", "6F", "Load A in L", &z80_ld_l_a},
  {"LD (HL),B", "70", "Load B in the value of address ((0xFF00) + HL)", &z80_ld_adr_hl_b},
  {"LD (HL),C", "71", "Load C in the value of address ((0xFF00) + HL)", &z80_ld_adr_hl_c},
  {"LD (HL),D", "72", "Load D in the value of address ((0xFF00) + HL)", &z80_ld_adr_hl_d},
  {"LD (HL),E", "73", "Load E in the value of address ((0xFF00) + HL)", &z80_ld_adr_hl_e},
  {"LD (HL),H", "74", "Load H in the value of address ((0xFF00) + HL)", &z80_ld_adr_hl_h},
  {"LD (HL),L", "75", "Load L in the value of address ((0xFF00) + HL)", &z80_ld_adr_hl_l},
  {"HALT", "76", "HALT", &z80_halt},
  {"LD (HL),A", "77", "Load A in the value of address ((0xFF00) + HL)", &z80_ld_adr_hl_a},
  {"LD A,B", "78", "Load B in A", &z80_ld_a_b},
  {"LD A,C", "79", "Load C in A", &z80_ld_a_c},
  {"LD A,D", "7A", "Load D in A", &z80_ld_a_d},
  {"LD A,E", "7B", "Load E in A", &z80_ld_a_e},
  {"LD A,H", "7C", "Load H in A", &z80_ld_a_h},
  {"LD A,L", "7D", "Load L in A", &z80_ld_a_l},
  {"LD A,(HL)", "7E", "Load the value stored in the address ((0xFF00) + HL) in A", &z80_ld_a_adr_hl},
  {"LD A,A", "7F", "Load A in A", &z80_ld_a_a},
  {"ADD A,B", "80", "Add B to A", &z80_add_a_b},
  {"ADD A,C", "81", "Add C to A", &z80_add_a_c},
  {"ADD A,D", "82", "Add D to A", &z80_add_a_d},
  {"ADD A,E", "83", "Add E to A", &z80_add_a_e},
  {"ADD A,H", "84", "Add H to A", &z80_add_a_h},
  {"ADD A,L", "85", "Add L to A", &z80_add_a_l},
  {"ADD A,(HL)","86", "Add the value stored in the address ((0xFF00) + HL) to A", &z80_add_a_adr_hl},
  {"ADD A,A", "87", "Add A to A", &z80_add_a_a},
  {"ADC A,B", "88", "Add (B + Carry Flag) to A", &z80_adc_a_b},
  {"ADC A,C", "89", "Add (C + Carry flag)"}
}
